mongo: {}
documentdb:
  database: treeherder-proxy

treeherder:
  apiUrl: https://treeherder.mozilla.org/api/

treeherderActions:
  routePrefix: taskcluster
  prefetch: 200

taskcluster:
  credentials: {}

treeherderTaskcluster:
  routePrefix: tc-treeherder
  prefetch: 200

treeherderProxy:
  port: 60025

redis: {}
pulse: {}

kue:
  logFailedJobs: false
  admin:
    port: 60024

repositoryMonitor:
  interval: 60000
  maxPushFetches: 200

commitPublisher:
  title: |
    Pushlog Commit Events
  description: |
    The pushlog events can be used to hook various other components into
    the act of commiting to a particuar repository (usually to kick off tests)
    this exchange is hopefuly a short lived thing which abstracts polling the
    pushlog for new data.

    Pushes will be monitored (via polling) and events will be sent as new data
    is available. If for some reason the service goes down previous commits
    will also be fetched and any missing data (up to a particular amount) will
    be sent as events...

try:
  enabled: true
  # Default url used when figuring out where to fetch task graph has some special
  # mustache parameters used to customize the path.
  #
  #   - alias: current key name
  #   - revision: revision of the change
  #   - path: sub path to repository
  #   - host: host of repository
  #
  defaultUrl: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/{{alias}}.yml"

  # If for some reason the task yaml is invalid we still would like to create a
  # task if for no other reason then to notify the user that this failed.
  # XXX: This url is temporary until a real one hits mozilla-central.
  errorTaskUrl: "https://gist.githubusercontent.com/gregarndt/8fc123be2408180c2f13/raw/d12f500faa334bc72cb1dd033e028773ac2476c8/error.yml"

  # Default scopes to use for projects which have no specific scopes of their own.
  defaultScopes:
    - queue:*
    - docker-worker:*
    - scheduler:*

  projects:
    # Try is the definitive example:
    try: # Note the keys match the "alias" which treeherder defines.
      # The url overrides the default url mapping and may include same mustache
      # parameters...
      # url: ...

      # The commit _must_ contain +tc to be scheduled...
      contains: 'try:'

      # The graph will be restricted to the following scopes this should ideally be
      # as locked down as possible.
      # scopes: []
      #
      scopes:
        - queue:*
        - scheduler:*
        - docker-worker:cache:*
        - docker-worker:image:*
        - docker-worker:capability:device:loopbackAudio
        - docker-worker:capability:device:loopbackVideo
        - docker-worker:relengapi-proxy:tooltool.download.internal
        - docker-worker:relengapi-proxy:tooltool.download.public
    mozilla-b2g34_v2_1s:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    mozilla-b2g44_v2_5:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    b2g-inbound:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    mozilla-inbound:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    fx-team:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    mozilla-central:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    cedar:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    cypress:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    alder:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"
    pine:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"  
