documentdb:
  database: treeherder-proxy-production

config:
  documentkey: production
  files:
    - production-treeherder-proxy.yml

treeherderActions:
  exchange: exchange/treeherder/v1/job-actions
  queue: mozilla-taskcluster-production-actions

treeherderTaskcluster:
  routePrefix: tc-treeherder
  queue: mozilla-taskcluster-production

kue:
  purgeCompleted: true
  prefix: production
