documentdb:
  database: treeherder-proxy-production

config:
  documentkey: production
  files:
    - production-treeherder-proxy.yml

treeherderTaskcluster:
  routePrefix: tc-treeherder
  queue: mozilla-taskcluster-production

kue:
  purgeCompleted: true
  prefix: production
