documentdb:
  database: treeherder-proxy-stage

config:
  documentkey: stage
  files:
    - stage-treeherder-proxy.yml

treeherderTaskcluster:
  routePrefix: tc-treeherder-stage
  queue: mozilla-taskcluster-stage

kue:
  prefix: stage
